apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: my-nginx
      image: kimsongha/my-nginx:latest
      ports:
        - containerPort: 80
